# Generated by Django 5.2.17 on 2026-09-27 16:41

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('text', models.TextField(max_length=500)),
                ('scores', core.fields.JSONListField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'анализ текста',
                'verbose_name_plural': 'анализы текста',
                'ordering': ['-created_at'],
            },
        ),
    ]
