# Generated by Django 5.2.17 on 2026-09-29 21:16

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('image', models.ImageField(upload_to='predictions/%Y/%m/%d')),
                ('labels', core.fields.JSONListField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'классификация изображения',
                'verbose_name_plural': 'классификации изображений',
                'ordering': ['-created_at'],
            },
        ),
    ]
